// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/requisites.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PartnerContext struct {
	PartnerID            string   `protobuf:"bytes,1,opt,name=partnerID,proto3" json:"partnerID,omitempty"`
	Context              []byte   `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartnerContext) Reset()         { *m = PartnerContext{} }
func (m *PartnerContext) String() string { return proto.CompactTextString(m) }
func (*PartnerContext) ProtoMessage()    {}
func (*PartnerContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{0}
}
func (m *PartnerContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartnerContext.Unmarshal(m, b)
}
func (m *PartnerContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartnerContext.Marshal(b, m, deterministic)
}
func (dst *PartnerContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartnerContext.Merge(dst, src)
}
func (m *PartnerContext) XXX_Size() int {
	return xxx_messageInfo_PartnerContext.Size(m)
}
func (m *PartnerContext) XXX_DiscardUnknown() {
	xxx_messageInfo_PartnerContext.DiscardUnknown(m)
}

var xxx_messageInfo_PartnerContext proto.InternalMessageInfo

func (m *PartnerContext) GetPartnerID() string {
	if m != nil {
		return m.PartnerID
	}
	return ""
}

func (m *PartnerContext) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

type Header struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{1}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Header) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SetBankDetailRequest struct {
	PartnerContext         *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID                 string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	DetailName             string          `protobuf:"bytes,3,opt,name=detailName,proto3" json:"detailName,omitempty"`
	BankIdentificationCode string          `protobuf:"bytes,4,opt,name=bankIdentificationCode,proto3" json:"bankIdentificationCode,omitempty"`
	BankName               string          `protobuf:"bytes,5,opt,name=bankName,proto3" json:"bankName,omitempty"`
	City                   string          `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Address                string          `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	CorrAccount            string          `protobuf:"bytes,8,opt,name=corrAccount,proto3" json:"corrAccount,omitempty"`
	CheckingAccount        string          `protobuf:"bytes,9,opt,name=checkingAccount,proto3" json:"checkingAccount,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}        `json:"-"`
	XXX_unrecognized       []byte          `json:"-"`
	XXX_sizecache          int32           `json:"-"`
}

func (m *SetBankDetailRequest) Reset()         { *m = SetBankDetailRequest{} }
func (m *SetBankDetailRequest) String() string { return proto.CompactTextString(m) }
func (*SetBankDetailRequest) ProtoMessage()    {}
func (*SetBankDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{2}
}
func (m *SetBankDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBankDetailRequest.Unmarshal(m, b)
}
func (m *SetBankDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBankDetailRequest.Marshal(b, m, deterministic)
}
func (dst *SetBankDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBankDetailRequest.Merge(dst, src)
}
func (m *SetBankDetailRequest) XXX_Size() int {
	return xxx_messageInfo_SetBankDetailRequest.Size(m)
}
func (m *SetBankDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBankDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetBankDetailRequest proto.InternalMessageInfo

func (m *SetBankDetailRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *SetBankDetailRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SetBankDetailRequest) GetDetailName() string {
	if m != nil {
		return m.DetailName
	}
	return ""
}

func (m *SetBankDetailRequest) GetBankIdentificationCode() string {
	if m != nil {
		return m.BankIdentificationCode
	}
	return ""
}

func (m *SetBankDetailRequest) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *SetBankDetailRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *SetBankDetailRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SetBankDetailRequest) GetCorrAccount() string {
	if m != nil {
		return m.CorrAccount
	}
	return ""
}

func (m *SetBankDetailRequest) GetCheckingAccount() string {
	if m != nil {
		return m.CheckingAccount
	}
	return ""
}

type SetBankDetailResponse struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	RequisiteID          string   `protobuf:"bytes,2,opt,name=requisiteID,proto3" json:"requisiteID,omitempty"`
	DefaultDetail        bool     `protobuf:"varint,3,opt,name=defaultDetail,proto3" json:"defaultDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetBankDetailResponse) Reset()         { *m = SetBankDetailResponse{} }
func (m *SetBankDetailResponse) String() string { return proto.CompactTextString(m) }
func (*SetBankDetailResponse) ProtoMessage()    {}
func (*SetBankDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{3}
}
func (m *SetBankDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBankDetailResponse.Unmarshal(m, b)
}
func (m *SetBankDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBankDetailResponse.Marshal(b, m, deterministic)
}
func (dst *SetBankDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBankDetailResponse.Merge(dst, src)
}
func (m *SetBankDetailResponse) XXX_Size() int {
	return xxx_messageInfo_SetBankDetailResponse.Size(m)
}
func (m *SetBankDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBankDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetBankDetailResponse proto.InternalMessageInfo

func (m *SetBankDetailResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SetBankDetailResponse) GetRequisiteID() string {
	if m != nil {
		return m.RequisiteID
	}
	return ""
}

func (m *SetBankDetailResponse) GetDefaultDetail() bool {
	if m != nil {
		return m.DefaultDetail
	}
	return false
}

type GetBankDetailsRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetBankDetailsRequest) Reset()         { *m = GetBankDetailsRequest{} }
func (m *GetBankDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetBankDetailsRequest) ProtoMessage()    {}
func (*GetBankDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{4}
}
func (m *GetBankDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBankDetailsRequest.Unmarshal(m, b)
}
func (m *GetBankDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBankDetailsRequest.Marshal(b, m, deterministic)
}
func (dst *GetBankDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBankDetailsRequest.Merge(dst, src)
}
func (m *GetBankDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetBankDetailsRequest.Size(m)
}
func (m *GetBankDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBankDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBankDetailsRequest proto.InternalMessageInfo

func (m *GetBankDetailsRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *GetBankDetailsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetBankDetailRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	RequisiteID          string          `protobuf:"bytes,3,opt,name=requisiteID,proto3" json:"requisiteID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetBankDetailRequest) Reset()         { *m = GetBankDetailRequest{} }
func (m *GetBankDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetBankDetailRequest) ProtoMessage()    {}
func (*GetBankDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{5}
}
func (m *GetBankDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBankDetailRequest.Unmarshal(m, b)
}
func (m *GetBankDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBankDetailRequest.Marshal(b, m, deterministic)
}
func (dst *GetBankDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBankDetailRequest.Merge(dst, src)
}
func (m *GetBankDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GetBankDetailRequest.Size(m)
}
func (m *GetBankDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBankDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBankDetailRequest proto.InternalMessageInfo

func (m *GetBankDetailRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *GetBankDetailRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetBankDetailRequest) GetRequisiteID() string {
	if m != nil {
		return m.RequisiteID
	}
	return ""
}

type GetBankDetailResponse struct {
	Header                 *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	RequisiteID            string   `protobuf:"bytes,2,opt,name=requisiteID,proto3" json:"requisiteID,omitempty"`
	DetailName             string   `protobuf:"bytes,3,opt,name=detailName,proto3" json:"detailName,omitempty"`
	BankIdentificationCode string   `protobuf:"bytes,4,opt,name=bankIdentificationCode,proto3" json:"bankIdentificationCode,omitempty"`
	BankName               string   `protobuf:"bytes,5,opt,name=bankName,proto3" json:"bankName,omitempty"`
	City                   string   `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Address                string   `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	CorrAccount            string   `protobuf:"bytes,8,opt,name=corrAccount,proto3" json:"corrAccount,omitempty"`
	CheckingAccount        string   `protobuf:"bytes,9,opt,name=checkingAccount,proto3" json:"checkingAccount,omitempty"`
	DefaultDetail          bool     `protobuf:"varint,10,opt,name=defaultDetail,proto3" json:"defaultDetail,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *GetBankDetailResponse) Reset()         { *m = GetBankDetailResponse{} }
func (m *GetBankDetailResponse) String() string { return proto.CompactTextString(m) }
func (*GetBankDetailResponse) ProtoMessage()    {}
func (*GetBankDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{6}
}
func (m *GetBankDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBankDetailResponse.Unmarshal(m, b)
}
func (m *GetBankDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBankDetailResponse.Marshal(b, m, deterministic)
}
func (dst *GetBankDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBankDetailResponse.Merge(dst, src)
}
func (m *GetBankDetailResponse) XXX_Size() int {
	return xxx_messageInfo_GetBankDetailResponse.Size(m)
}
func (m *GetBankDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBankDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBankDetailResponse proto.InternalMessageInfo

func (m *GetBankDetailResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetBankDetailResponse) GetRequisiteID() string {
	if m != nil {
		return m.RequisiteID
	}
	return ""
}

func (m *GetBankDetailResponse) GetDetailName() string {
	if m != nil {
		return m.DetailName
	}
	return ""
}

func (m *GetBankDetailResponse) GetBankIdentificationCode() string {
	if m != nil {
		return m.BankIdentificationCode
	}
	return ""
}

func (m *GetBankDetailResponse) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *GetBankDetailResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *GetBankDetailResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetBankDetailResponse) GetCorrAccount() string {
	if m != nil {
		return m.CorrAccount
	}
	return ""
}

func (m *GetBankDetailResponse) GetCheckingAccount() string {
	if m != nil {
		return m.CheckingAccount
	}
	return ""
}

func (m *GetBankDetailResponse) GetDefaultDetail() bool {
	if m != nil {
		return m.DefaultDetail
	}
	return false
}

type BankDetailInfo struct {
	RequisiteID            string   `protobuf:"bytes,1,opt,name=requisiteID,proto3" json:"requisiteID,omitempty"`
	DetailName             string   `protobuf:"bytes,2,opt,name=detailName,proto3" json:"detailName,omitempty"`
	BankIdentificationCode string   `protobuf:"bytes,3,opt,name=bankIdentificationCode,proto3" json:"bankIdentificationCode,omitempty"`
	BankName               string   `protobuf:"bytes,4,opt,name=bankName,proto3" json:"bankName,omitempty"`
	City                   string   `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Address                string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	CorrAccount            string   `protobuf:"bytes,7,opt,name=corrAccount,proto3" json:"corrAccount,omitempty"`
	CheckingAccount        string   `protobuf:"bytes,8,opt,name=checkingAccount,proto3" json:"checkingAccount,omitempty"`
	DefaultDetail          bool     `protobuf:"varint,9,opt,name=defaultDetail,proto3" json:"defaultDetail,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *BankDetailInfo) Reset()         { *m = BankDetailInfo{} }
func (m *BankDetailInfo) String() string { return proto.CompactTextString(m) }
func (*BankDetailInfo) ProtoMessage()    {}
func (*BankDetailInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{7}
}
func (m *BankDetailInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankDetailInfo.Unmarshal(m, b)
}
func (m *BankDetailInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankDetailInfo.Marshal(b, m, deterministic)
}
func (dst *BankDetailInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankDetailInfo.Merge(dst, src)
}
func (m *BankDetailInfo) XXX_Size() int {
	return xxx_messageInfo_BankDetailInfo.Size(m)
}
func (m *BankDetailInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BankDetailInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BankDetailInfo proto.InternalMessageInfo

func (m *BankDetailInfo) GetRequisiteID() string {
	if m != nil {
		return m.RequisiteID
	}
	return ""
}

func (m *BankDetailInfo) GetDetailName() string {
	if m != nil {
		return m.DetailName
	}
	return ""
}

func (m *BankDetailInfo) GetBankIdentificationCode() string {
	if m != nil {
		return m.BankIdentificationCode
	}
	return ""
}

func (m *BankDetailInfo) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *BankDetailInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *BankDetailInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *BankDetailInfo) GetCorrAccount() string {
	if m != nil {
		return m.CorrAccount
	}
	return ""
}

func (m *BankDetailInfo) GetCheckingAccount() string {
	if m != nil {
		return m.CheckingAccount
	}
	return ""
}

func (m *BankDetailInfo) GetDefaultDetail() bool {
	if m != nil {
		return m.DefaultDetail
	}
	return false
}

type GetBankDetailsResponse struct {
	Header               *Header           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	BankDetailInfo       []*BankDetailInfo `protobuf:"bytes,2,rep,name=bankDetailInfo,proto3" json:"bankDetailInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetBankDetailsResponse) Reset()         { *m = GetBankDetailsResponse{} }
func (m *GetBankDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*GetBankDetailsResponse) ProtoMessage()    {}
func (*GetBankDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{8}
}
func (m *GetBankDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBankDetailsResponse.Unmarshal(m, b)
}
func (m *GetBankDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBankDetailsResponse.Marshal(b, m, deterministic)
}
func (dst *GetBankDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBankDetailsResponse.Merge(dst, src)
}
func (m *GetBankDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_GetBankDetailsResponse.Size(m)
}
func (m *GetBankDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBankDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBankDetailsResponse proto.InternalMessageInfo

func (m *GetBankDetailsResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetBankDetailsResponse) GetBankDetailInfo() []*BankDetailInfo {
	if m != nil {
		return m.BankDetailInfo
	}
	return nil
}

type SetBusinessInfoRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	CompanyName          string          `protobuf:"bytes,3,opt,name=companyName,proto3" json:"companyName,omitempty"`
	Inn                  string          `protobuf:"bytes,4,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp                  string          `protobuf:"bytes,5,opt,name=kpp,proto3" json:"kpp,omitempty"`
	Ogrn                 string          `protobuf:"bytes,6,opt,name=ogrn,proto3" json:"ogrn,omitempty"`
	LegalAddress         string          `protobuf:"bytes,7,opt,name=legalAddress,proto3" json:"legalAddress,omitempty"`
	PhysicalAddress      string          `protobuf:"bytes,8,opt,name=physicalAddress,proto3" json:"physicalAddress,omitempty"`
	ChiefUserFIO         string          `protobuf:"bytes,9,opt,name=chiefUserFIO,proto3" json:"chiefUserFIO,omitempty"`
	ChiefUserPosition    string          `protobuf:"bytes,10,opt,name=chiefUserPosition,proto3" json:"chiefUserPosition,omitempty"`
	GroundsForActions    string          `protobuf:"bytes,11,opt,name=groundsForActions,proto3" json:"groundsForActions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SetBusinessInfoRequest) Reset()         { *m = SetBusinessInfoRequest{} }
func (m *SetBusinessInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SetBusinessInfoRequest) ProtoMessage()    {}
func (*SetBusinessInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{9}
}
func (m *SetBusinessInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBusinessInfoRequest.Unmarshal(m, b)
}
func (m *SetBusinessInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBusinessInfoRequest.Marshal(b, m, deterministic)
}
func (dst *SetBusinessInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBusinessInfoRequest.Merge(dst, src)
}
func (m *SetBusinessInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SetBusinessInfoRequest.Size(m)
}
func (m *SetBusinessInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBusinessInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetBusinessInfoRequest proto.InternalMessageInfo

func (m *SetBusinessInfoRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *SetBusinessInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SetBusinessInfoRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *SetBusinessInfoRequest) GetInn() string {
	if m != nil {
		return m.Inn
	}
	return ""
}

func (m *SetBusinessInfoRequest) GetKpp() string {
	if m != nil {
		return m.Kpp
	}
	return ""
}

func (m *SetBusinessInfoRequest) GetOgrn() string {
	if m != nil {
		return m.Ogrn
	}
	return ""
}

func (m *SetBusinessInfoRequest) GetLegalAddress() string {
	if m != nil {
		return m.LegalAddress
	}
	return ""
}

func (m *SetBusinessInfoRequest) GetPhysicalAddress() string {
	if m != nil {
		return m.PhysicalAddress
	}
	return ""
}

func (m *SetBusinessInfoRequest) GetChiefUserFIO() string {
	if m != nil {
		return m.ChiefUserFIO
	}
	return ""
}

func (m *SetBusinessInfoRequest) GetChiefUserPosition() string {
	if m != nil {
		return m.ChiefUserPosition
	}
	return ""
}

func (m *SetBusinessInfoRequest) GetGroundsForActions() string {
	if m != nil {
		return m.GroundsForActions
	}
	return ""
}

type InfoIdResponse struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	InfoID               string   `protobuf:"bytes,2,opt,name=infoID,proto3" json:"infoID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoIdResponse) Reset()         { *m = InfoIdResponse{} }
func (m *InfoIdResponse) String() string { return proto.CompactTextString(m) }
func (*InfoIdResponse) ProtoMessage()    {}
func (*InfoIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{10}
}
func (m *InfoIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoIdResponse.Unmarshal(m, b)
}
func (m *InfoIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoIdResponse.Marshal(b, m, deterministic)
}
func (dst *InfoIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoIdResponse.Merge(dst, src)
}
func (m *InfoIdResponse) XXX_Size() int {
	return xxx_messageInfo_InfoIdResponse.Size(m)
}
func (m *InfoIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoIdResponse proto.InternalMessageInfo

func (m *InfoIdResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *InfoIdResponse) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

type GetInfoRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	UserType             uint32          `protobuf:"varint,3,opt,name=userType,proto3" json:"userType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{11}
}
func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(dst, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

func (m *GetInfoRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *GetInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetInfoRequest) GetUserType() uint32 {
	if m != nil {
		return m.UserType
	}
	return 0
}

type BusinessInfoResponse struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	InfoID               string   `protobuf:"bytes,2,opt,name=infoID,proto3" json:"infoID,omitempty"`
	CompanyName          string   `protobuf:"bytes,3,opt,name=companyName,proto3" json:"companyName,omitempty"`
	Inn                  string   `protobuf:"bytes,4,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp                  string   `protobuf:"bytes,5,opt,name=kpp,proto3" json:"kpp,omitempty"`
	Ogrn                 string   `protobuf:"bytes,6,opt,name=ogrn,proto3" json:"ogrn,omitempty"`
	LegalAddress         string   `protobuf:"bytes,7,opt,name=legalAddress,proto3" json:"legalAddress,omitempty"`
	PhysicalAddress      string   `protobuf:"bytes,8,opt,name=physicalAddress,proto3" json:"physicalAddress,omitempty"`
	ChiefUserFIO         string   `protobuf:"bytes,9,opt,name=chiefUserFIO,proto3" json:"chiefUserFIO,omitempty"`
	ChiefUserPosition    string   `protobuf:"bytes,10,opt,name=chiefUserPosition,proto3" json:"chiefUserPosition,omitempty"`
	GroundsForActions    string   `protobuf:"bytes,11,opt,name=groundsForActions,proto3" json:"groundsForActions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusinessInfoResponse) Reset()         { *m = BusinessInfoResponse{} }
func (m *BusinessInfoResponse) String() string { return proto.CompactTextString(m) }
func (*BusinessInfoResponse) ProtoMessage()    {}
func (*BusinessInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{12}
}
func (m *BusinessInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessInfoResponse.Unmarshal(m, b)
}
func (m *BusinessInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessInfoResponse.Marshal(b, m, deterministic)
}
func (dst *BusinessInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessInfoResponse.Merge(dst, src)
}
func (m *BusinessInfoResponse) XXX_Size() int {
	return xxx_messageInfo_BusinessInfoResponse.Size(m)
}
func (m *BusinessInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessInfoResponse proto.InternalMessageInfo

func (m *BusinessInfoResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BusinessInfoResponse) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *BusinessInfoResponse) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *BusinessInfoResponse) GetInn() string {
	if m != nil {
		return m.Inn
	}
	return ""
}

func (m *BusinessInfoResponse) GetKpp() string {
	if m != nil {
		return m.Kpp
	}
	return ""
}

func (m *BusinessInfoResponse) GetOgrn() string {
	if m != nil {
		return m.Ogrn
	}
	return ""
}

func (m *BusinessInfoResponse) GetLegalAddress() string {
	if m != nil {
		return m.LegalAddress
	}
	return ""
}

func (m *BusinessInfoResponse) GetPhysicalAddress() string {
	if m != nil {
		return m.PhysicalAddress
	}
	return ""
}

func (m *BusinessInfoResponse) GetChiefUserFIO() string {
	if m != nil {
		return m.ChiefUserFIO
	}
	return ""
}

func (m *BusinessInfoResponse) GetChiefUserPosition() string {
	if m != nil {
		return m.ChiefUserPosition
	}
	return ""
}

func (m *BusinessInfoResponse) GetGroundsForActions() string {
	if m != nil {
		return m.GroundsForActions
	}
	return ""
}

type SetBusinessContactInfoRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	ContactUserFIO       string          `protobuf:"bytes,3,opt,name=contactUserFIO,proto3" json:"contactUserFIO,omitempty"`
	ContactUserPosition  string          `protobuf:"bytes,4,opt,name=contactUserPosition,proto3" json:"contactUserPosition,omitempty"`
	ContactUserPhone     string          `protobuf:"bytes,5,opt,name=contactUserPhone,proto3" json:"contactUserPhone,omitempty"`
	ContactUserEmail     string          `protobuf:"bytes,6,opt,name=contactUserEmail,proto3" json:"contactUserEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SetBusinessContactInfoRequest) Reset()         { *m = SetBusinessContactInfoRequest{} }
func (m *SetBusinessContactInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SetBusinessContactInfoRequest) ProtoMessage()    {}
func (*SetBusinessContactInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{13}
}
func (m *SetBusinessContactInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBusinessContactInfoRequest.Unmarshal(m, b)
}
func (m *SetBusinessContactInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBusinessContactInfoRequest.Marshal(b, m, deterministic)
}
func (dst *SetBusinessContactInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBusinessContactInfoRequest.Merge(dst, src)
}
func (m *SetBusinessContactInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SetBusinessContactInfoRequest.Size(m)
}
func (m *SetBusinessContactInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBusinessContactInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetBusinessContactInfoRequest proto.InternalMessageInfo

func (m *SetBusinessContactInfoRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *SetBusinessContactInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SetBusinessContactInfoRequest) GetContactUserFIO() string {
	if m != nil {
		return m.ContactUserFIO
	}
	return ""
}

func (m *SetBusinessContactInfoRequest) GetContactUserPosition() string {
	if m != nil {
		return m.ContactUserPosition
	}
	return ""
}

func (m *SetBusinessContactInfoRequest) GetContactUserPhone() string {
	if m != nil {
		return m.ContactUserPhone
	}
	return ""
}

func (m *SetBusinessContactInfoRequest) GetContactUserEmail() string {
	if m != nil {
		return m.ContactUserEmail
	}
	return ""
}

type BusinessContactInfoResponse struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	InfoID               string   `protobuf:"bytes,2,opt,name=infoID,proto3" json:"infoID,omitempty"`
	ContactUserFIO       string   `protobuf:"bytes,3,opt,name=contactUserFIO,proto3" json:"contactUserFIO,omitempty"`
	ContactUserPosition  string   `protobuf:"bytes,4,opt,name=contactUserPosition,proto3" json:"contactUserPosition,omitempty"`
	ContactUserPhone     string   `protobuf:"bytes,5,opt,name=contactUserPhone,proto3" json:"contactUserPhone,omitempty"`
	ContactUserEmail     string   `protobuf:"bytes,6,opt,name=contactUserEmail,proto3" json:"contactUserEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusinessContactInfoResponse) Reset()         { *m = BusinessContactInfoResponse{} }
func (m *BusinessContactInfoResponse) String() string { return proto.CompactTextString(m) }
func (*BusinessContactInfoResponse) ProtoMessage()    {}
func (*BusinessContactInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{14}
}
func (m *BusinessContactInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessContactInfoResponse.Unmarshal(m, b)
}
func (m *BusinessContactInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessContactInfoResponse.Marshal(b, m, deterministic)
}
func (dst *BusinessContactInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessContactInfoResponse.Merge(dst, src)
}
func (m *BusinessContactInfoResponse) XXX_Size() int {
	return xxx_messageInfo_BusinessContactInfoResponse.Size(m)
}
func (m *BusinessContactInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessContactInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessContactInfoResponse proto.InternalMessageInfo

func (m *BusinessContactInfoResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BusinessContactInfoResponse) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *BusinessContactInfoResponse) GetContactUserFIO() string {
	if m != nil {
		return m.ContactUserFIO
	}
	return ""
}

func (m *BusinessContactInfoResponse) GetContactUserPosition() string {
	if m != nil {
		return m.ContactUserPosition
	}
	return ""
}

func (m *BusinessContactInfoResponse) GetContactUserPhone() string {
	if m != nil {
		return m.ContactUserPhone
	}
	return ""
}

func (m *BusinessContactInfoResponse) GetContactUserEmail() string {
	if m != nil {
		return m.ContactUserEmail
	}
	return ""
}

type UpdateBusinessInfoRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	InfoID               string          `protobuf:"bytes,3,opt,name=infoID,proto3" json:"infoID,omitempty"`
	CompanyName          string          `protobuf:"bytes,4,opt,name=companyName,proto3" json:"companyName,omitempty"`
	Inn                  string          `protobuf:"bytes,5,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp                  string          `protobuf:"bytes,6,opt,name=kpp,proto3" json:"kpp,omitempty"`
	Ogrn                 string          `protobuf:"bytes,7,opt,name=ogrn,proto3" json:"ogrn,omitempty"`
	LegalAddress         string          `protobuf:"bytes,8,opt,name=legalAddress,proto3" json:"legalAddress,omitempty"`
	PhysicalAddress      string          `protobuf:"bytes,9,opt,name=physicalAddress,proto3" json:"physicalAddress,omitempty"`
	ChiefUserFIO         string          `protobuf:"bytes,10,opt,name=chiefUserFIO,proto3" json:"chiefUserFIO,omitempty"`
	ChiefUserPosition    string          `protobuf:"bytes,11,opt,name=chiefUserPosition,proto3" json:"chiefUserPosition,omitempty"`
	GroundsForActions    string          `protobuf:"bytes,12,opt,name=groundsForActions,proto3" json:"groundsForActions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateBusinessInfoRequest) Reset()         { *m = UpdateBusinessInfoRequest{} }
func (m *UpdateBusinessInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBusinessInfoRequest) ProtoMessage()    {}
func (*UpdateBusinessInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{15}
}
func (m *UpdateBusinessInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBusinessInfoRequest.Unmarshal(m, b)
}
func (m *UpdateBusinessInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBusinessInfoRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateBusinessInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBusinessInfoRequest.Merge(dst, src)
}
func (m *UpdateBusinessInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBusinessInfoRequest.Size(m)
}
func (m *UpdateBusinessInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBusinessInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBusinessInfoRequest proto.InternalMessageInfo

func (m *UpdateBusinessInfoRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *UpdateBusinessInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateBusinessInfoRequest) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *UpdateBusinessInfoRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *UpdateBusinessInfoRequest) GetInn() string {
	if m != nil {
		return m.Inn
	}
	return ""
}

func (m *UpdateBusinessInfoRequest) GetKpp() string {
	if m != nil {
		return m.Kpp
	}
	return ""
}

func (m *UpdateBusinessInfoRequest) GetOgrn() string {
	if m != nil {
		return m.Ogrn
	}
	return ""
}

func (m *UpdateBusinessInfoRequest) GetLegalAddress() string {
	if m != nil {
		return m.LegalAddress
	}
	return ""
}

func (m *UpdateBusinessInfoRequest) GetPhysicalAddress() string {
	if m != nil {
		return m.PhysicalAddress
	}
	return ""
}

func (m *UpdateBusinessInfoRequest) GetChiefUserFIO() string {
	if m != nil {
		return m.ChiefUserFIO
	}
	return ""
}

func (m *UpdateBusinessInfoRequest) GetChiefUserPosition() string {
	if m != nil {
		return m.ChiefUserPosition
	}
	return ""
}

func (m *UpdateBusinessInfoRequest) GetGroundsForActions() string {
	if m != nil {
		return m.GroundsForActions
	}
	return ""
}

type UpdateBusinessContactInfoRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	InfoID               string          `protobuf:"bytes,3,opt,name=infoID,proto3" json:"infoID,omitempty"`
	ContactUserFIO       string          `protobuf:"bytes,4,opt,name=contactUserFIO,proto3" json:"contactUserFIO,omitempty"`
	ContactUserPosition  string          `protobuf:"bytes,5,opt,name=contactUserPosition,proto3" json:"contactUserPosition,omitempty"`
	ContactUserPhone     string          `protobuf:"bytes,6,opt,name=contactUserPhone,proto3" json:"contactUserPhone,omitempty"`
	ContactUserEmail     string          `protobuf:"bytes,7,opt,name=contactUserEmail,proto3" json:"contactUserEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateBusinessContactInfoRequest) Reset()         { *m = UpdateBusinessContactInfoRequest{} }
func (m *UpdateBusinessContactInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBusinessContactInfoRequest) ProtoMessage()    {}
func (*UpdateBusinessContactInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{16}
}
func (m *UpdateBusinessContactInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBusinessContactInfoRequest.Unmarshal(m, b)
}
func (m *UpdateBusinessContactInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBusinessContactInfoRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateBusinessContactInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBusinessContactInfoRequest.Merge(dst, src)
}
func (m *UpdateBusinessContactInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBusinessContactInfoRequest.Size(m)
}
func (m *UpdateBusinessContactInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBusinessContactInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBusinessContactInfoRequest proto.InternalMessageInfo

func (m *UpdateBusinessContactInfoRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *UpdateBusinessContactInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateBusinessContactInfoRequest) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *UpdateBusinessContactInfoRequest) GetContactUserFIO() string {
	if m != nil {
		return m.ContactUserFIO
	}
	return ""
}

func (m *UpdateBusinessContactInfoRequest) GetContactUserPosition() string {
	if m != nil {
		return m.ContactUserPosition
	}
	return ""
}

func (m *UpdateBusinessContactInfoRequest) GetContactUserPhone() string {
	if m != nil {
		return m.ContactUserPhone
	}
	return ""
}

func (m *UpdateBusinessContactInfoRequest) GetContactUserEmail() string {
	if m != nil {
		return m.ContactUserEmail
	}
	return ""
}

type UpdateDefaultPaymentsRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	RequisiteID          string          `protobuf:"bytes,3,opt,name=requisiteID,proto3" json:"requisiteID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateDefaultPaymentsRequest) Reset()         { *m = UpdateDefaultPaymentsRequest{} }
func (m *UpdateDefaultPaymentsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDefaultPaymentsRequest) ProtoMessage()    {}
func (*UpdateDefaultPaymentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{17}
}
func (m *UpdateDefaultPaymentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDefaultPaymentsRequest.Unmarshal(m, b)
}
func (m *UpdateDefaultPaymentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDefaultPaymentsRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateDefaultPaymentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDefaultPaymentsRequest.Merge(dst, src)
}
func (m *UpdateDefaultPaymentsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDefaultPaymentsRequest.Size(m)
}
func (m *UpdateDefaultPaymentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDefaultPaymentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDefaultPaymentsRequest proto.InternalMessageInfo

func (m *UpdateDefaultPaymentsRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *UpdateDefaultPaymentsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateDefaultPaymentsRequest) GetRequisiteID() string {
	if m != nil {
		return m.RequisiteID
	}
	return ""
}

type UpdateDefaultPaymentsResponse struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	DefaultPayment       bool     `protobuf:"varint,2,opt,name=defaultPayment,proto3" json:"defaultPayment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDefaultPaymentsResponse) Reset()         { *m = UpdateDefaultPaymentsResponse{} }
func (m *UpdateDefaultPaymentsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateDefaultPaymentsResponse) ProtoMessage()    {}
func (*UpdateDefaultPaymentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{18}
}
func (m *UpdateDefaultPaymentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDefaultPaymentsResponse.Unmarshal(m, b)
}
func (m *UpdateDefaultPaymentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDefaultPaymentsResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateDefaultPaymentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDefaultPaymentsResponse.Merge(dst, src)
}
func (m *UpdateDefaultPaymentsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateDefaultPaymentsResponse.Size(m)
}
func (m *UpdateDefaultPaymentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDefaultPaymentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDefaultPaymentsResponse proto.InternalMessageInfo

func (m *UpdateDefaultPaymentsResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UpdateDefaultPaymentsResponse) GetDefaultPayment() bool {
	if m != nil {
		return m.DefaultPayment
	}
	return false
}

type SetBankCardRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Pan                  string          `protobuf:"bytes,3,opt,name=pan,proto3" json:"pan,omitempty"`
	CardHolder           string          `protobuf:"bytes,4,opt,name=cardHolder,proto3" json:"cardHolder,omitempty"`
	Expiry               string          `protobuf:"bytes,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SetBankCardRequest) Reset()         { *m = SetBankCardRequest{} }
func (m *SetBankCardRequest) String() string { return proto.CompactTextString(m) }
func (*SetBankCardRequest) ProtoMessage()    {}
func (*SetBankCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{19}
}
func (m *SetBankCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBankCardRequest.Unmarshal(m, b)
}
func (m *SetBankCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBankCardRequest.Marshal(b, m, deterministic)
}
func (dst *SetBankCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBankCardRequest.Merge(dst, src)
}
func (m *SetBankCardRequest) XXX_Size() int {
	return xxx_messageInfo_SetBankCardRequest.Size(m)
}
func (m *SetBankCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBankCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetBankCardRequest proto.InternalMessageInfo

func (m *SetBankCardRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *SetBankCardRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SetBankCardRequest) GetPan() string {
	if m != nil {
		return m.Pan
	}
	return ""
}

func (m *SetBankCardRequest) GetCardHolder() string {
	if m != nil {
		return m.CardHolder
	}
	return ""
}

func (m *SetBankCardRequest) GetExpiry() string {
	if m != nil {
		return m.Expiry
	}
	return ""
}

type SetBankCardResponse struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CardID               string   `protobuf:"bytes,2,opt,name=cardID,proto3" json:"cardID,omitempty"`
	DefaultCard          bool     `protobuf:"varint,3,opt,name=defaultCard,proto3" json:"defaultCard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetBankCardResponse) Reset()         { *m = SetBankCardResponse{} }
func (m *SetBankCardResponse) String() string { return proto.CompactTextString(m) }
func (*SetBankCardResponse) ProtoMessage()    {}
func (*SetBankCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{20}
}
func (m *SetBankCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBankCardResponse.Unmarshal(m, b)
}
func (m *SetBankCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBankCardResponse.Marshal(b, m, deterministic)
}
func (dst *SetBankCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBankCardResponse.Merge(dst, src)
}
func (m *SetBankCardResponse) XXX_Size() int {
	return xxx_messageInfo_SetBankCardResponse.Size(m)
}
func (m *SetBankCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBankCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetBankCardResponse proto.InternalMessageInfo

func (m *SetBankCardResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SetBankCardResponse) GetCardID() string {
	if m != nil {
		return m.CardID
	}
	return ""
}

func (m *SetBankCardResponse) GetDefaultCard() bool {
	if m != nil {
		return m.DefaultCard
	}
	return false
}

type GetBankCardsRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetBankCardsRequest) Reset()         { *m = GetBankCardsRequest{} }
func (m *GetBankCardsRequest) String() string { return proto.CompactTextString(m) }
func (*GetBankCardsRequest) ProtoMessage()    {}
func (*GetBankCardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{21}
}
func (m *GetBankCardsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBankCardsRequest.Unmarshal(m, b)
}
func (m *GetBankCardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBankCardsRequest.Marshal(b, m, deterministic)
}
func (dst *GetBankCardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBankCardsRequest.Merge(dst, src)
}
func (m *GetBankCardsRequest) XXX_Size() int {
	return xxx_messageInfo_GetBankCardsRequest.Size(m)
}
func (m *GetBankCardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBankCardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBankCardsRequest proto.InternalMessageInfo

func (m *GetBankCardsRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *GetBankCardsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetBankCardRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	CardID               string          `protobuf:"bytes,3,opt,name=cardID,proto3" json:"cardID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetBankCardRequest) Reset()         { *m = GetBankCardRequest{} }
func (m *GetBankCardRequest) String() string { return proto.CompactTextString(m) }
func (*GetBankCardRequest) ProtoMessage()    {}
func (*GetBankCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{22}
}
func (m *GetBankCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBankCardRequest.Unmarshal(m, b)
}
func (m *GetBankCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBankCardRequest.Marshal(b, m, deterministic)
}
func (dst *GetBankCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBankCardRequest.Merge(dst, src)
}
func (m *GetBankCardRequest) XXX_Size() int {
	return xxx_messageInfo_GetBankCardRequest.Size(m)
}
func (m *GetBankCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBankCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBankCardRequest proto.InternalMessageInfo

func (m *GetBankCardRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *GetBankCardRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetBankCardRequest) GetCardID() string {
	if m != nil {
		return m.CardID
	}
	return ""
}

type GetBankCardResponse struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CardID               string   `protobuf:"bytes,2,opt,name=cardID,proto3" json:"cardID,omitempty"`
	Pan                  string   `protobuf:"bytes,3,opt,name=pan,proto3" json:"pan,omitempty"`
	CardHolder           string   `protobuf:"bytes,4,opt,name=cardHolder,proto3" json:"cardHolder,omitempty"`
	Expiry               string   `protobuf:"bytes,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	DefaultCard          bool     `protobuf:"varint,6,opt,name=defaultCard,proto3" json:"defaultCard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBankCardResponse) Reset()         { *m = GetBankCardResponse{} }
func (m *GetBankCardResponse) String() string { return proto.CompactTextString(m) }
func (*GetBankCardResponse) ProtoMessage()    {}
func (*GetBankCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{23}
}
func (m *GetBankCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBankCardResponse.Unmarshal(m, b)
}
func (m *GetBankCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBankCardResponse.Marshal(b, m, deterministic)
}
func (dst *GetBankCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBankCardResponse.Merge(dst, src)
}
func (m *GetBankCardResponse) XXX_Size() int {
	return xxx_messageInfo_GetBankCardResponse.Size(m)
}
func (m *GetBankCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBankCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBankCardResponse proto.InternalMessageInfo

func (m *GetBankCardResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetBankCardResponse) GetCardID() string {
	if m != nil {
		return m.CardID
	}
	return ""
}

func (m *GetBankCardResponse) GetPan() string {
	if m != nil {
		return m.Pan
	}
	return ""
}

func (m *GetBankCardResponse) GetCardHolder() string {
	if m != nil {
		return m.CardHolder
	}
	return ""
}

func (m *GetBankCardResponse) GetExpiry() string {
	if m != nil {
		return m.Expiry
	}
	return ""
}

func (m *GetBankCardResponse) GetDefaultCard() bool {
	if m != nil {
		return m.DefaultCard
	}
	return false
}

type BankCardInfo struct {
	CardID               string   `protobuf:"bytes,1,opt,name=cardID,proto3" json:"cardID,omitempty"`
	Pan                  string   `protobuf:"bytes,2,opt,name=pan,proto3" json:"pan,omitempty"`
	CardHolder           string   `protobuf:"bytes,3,opt,name=cardHolder,proto3" json:"cardHolder,omitempty"`
	Expiry               string   `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	DefaultCard          bool     `protobuf:"varint,5,opt,name=defaultCard,proto3" json:"defaultCard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankCardInfo) Reset()         { *m = BankCardInfo{} }
func (m *BankCardInfo) String() string { return proto.CompactTextString(m) }
func (*BankCardInfo) ProtoMessage()    {}
func (*BankCardInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{24}
}
func (m *BankCardInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankCardInfo.Unmarshal(m, b)
}
func (m *BankCardInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankCardInfo.Marshal(b, m, deterministic)
}
func (dst *BankCardInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankCardInfo.Merge(dst, src)
}
func (m *BankCardInfo) XXX_Size() int {
	return xxx_messageInfo_BankCardInfo.Size(m)
}
func (m *BankCardInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BankCardInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BankCardInfo proto.InternalMessageInfo

func (m *BankCardInfo) GetCardID() string {
	if m != nil {
		return m.CardID
	}
	return ""
}

func (m *BankCardInfo) GetPan() string {
	if m != nil {
		return m.Pan
	}
	return ""
}

func (m *BankCardInfo) GetCardHolder() string {
	if m != nil {
		return m.CardHolder
	}
	return ""
}

func (m *BankCardInfo) GetExpiry() string {
	if m != nil {
		return m.Expiry
	}
	return ""
}

func (m *BankCardInfo) GetDefaultCard() bool {
	if m != nil {
		return m.DefaultCard
	}
	return false
}

type GetBankCardsResponse struct {
	Header               *Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	BankCardInfo         []*BankCardInfo `protobuf:"bytes,2,rep,name=bankCardInfo,proto3" json:"bankCardInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetBankCardsResponse) Reset()         { *m = GetBankCardsResponse{} }
func (m *GetBankCardsResponse) String() string { return proto.CompactTextString(m) }
func (*GetBankCardsResponse) ProtoMessage()    {}
func (*GetBankCardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{25}
}
func (m *GetBankCardsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBankCardsResponse.Unmarshal(m, b)
}
func (m *GetBankCardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBankCardsResponse.Marshal(b, m, deterministic)
}
func (dst *GetBankCardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBankCardsResponse.Merge(dst, src)
}
func (m *GetBankCardsResponse) XXX_Size() int {
	return xxx_messageInfo_GetBankCardsResponse.Size(m)
}
func (m *GetBankCardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBankCardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBankCardsResponse proto.InternalMessageInfo

func (m *GetBankCardsResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetBankCardsResponse) GetBankCardInfo() []*BankCardInfo {
	if m != nil {
		return m.BankCardInfo
	}
	return nil
}

type SetCustomerInfoRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	FIO                  string          `protobuf:"bytes,3,opt,name=FIO,json=fIO,proto3" json:"FIO,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SetCustomerInfoRequest) Reset()         { *m = SetCustomerInfoRequest{} }
func (m *SetCustomerInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SetCustomerInfoRequest) ProtoMessage()    {}
func (*SetCustomerInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{26}
}
func (m *SetCustomerInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCustomerInfoRequest.Unmarshal(m, b)
}
func (m *SetCustomerInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCustomerInfoRequest.Marshal(b, m, deterministic)
}
func (dst *SetCustomerInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCustomerInfoRequest.Merge(dst, src)
}
func (m *SetCustomerInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SetCustomerInfoRequest.Size(m)
}
func (m *SetCustomerInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCustomerInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetCustomerInfoRequest proto.InternalMessageInfo

func (m *SetCustomerInfoRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *SetCustomerInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SetCustomerInfoRequest) GetFIO() string {
	if m != nil {
		return m.FIO
	}
	return ""
}

type CustomerInfoResponse struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	InfoID               string   `protobuf:"bytes,2,opt,name=infoID,proto3" json:"infoID,omitempty"`
	Fio                  string   `protobuf:"bytes,3,opt,name=fio,proto3" json:"fio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerInfoResponse) Reset()         { *m = CustomerInfoResponse{} }
func (m *CustomerInfoResponse) String() string { return proto.CompactTextString(m) }
func (*CustomerInfoResponse) ProtoMessage()    {}
func (*CustomerInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{27}
}
func (m *CustomerInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerInfoResponse.Unmarshal(m, b)
}
func (m *CustomerInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerInfoResponse.Marshal(b, m, deterministic)
}
func (dst *CustomerInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerInfoResponse.Merge(dst, src)
}
func (m *CustomerInfoResponse) XXX_Size() int {
	return xxx_messageInfo_CustomerInfoResponse.Size(m)
}
func (m *CustomerInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerInfoResponse proto.InternalMessageInfo

func (m *CustomerInfoResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CustomerInfoResponse) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *CustomerInfoResponse) GetFio() string {
	if m != nil {
		return m.Fio
	}
	return ""
}

type SetCustomerContactInfoRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	ContactUserPhone     string          `protobuf:"bytes,3,opt,name=contactUserPhone,proto3" json:"contactUserPhone,omitempty"`
	ContactUserEmail     string          `protobuf:"bytes,4,opt,name=contactUserEmail,proto3" json:"contactUserEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SetCustomerContactInfoRequest) Reset()         { *m = SetCustomerContactInfoRequest{} }
func (m *SetCustomerContactInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SetCustomerContactInfoRequest) ProtoMessage()    {}
func (*SetCustomerContactInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{28}
}
func (m *SetCustomerContactInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCustomerContactInfoRequest.Unmarshal(m, b)
}
func (m *SetCustomerContactInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCustomerContactInfoRequest.Marshal(b, m, deterministic)
}
func (dst *SetCustomerContactInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCustomerContactInfoRequest.Merge(dst, src)
}
func (m *SetCustomerContactInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SetCustomerContactInfoRequest.Size(m)
}
func (m *SetCustomerContactInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCustomerContactInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetCustomerContactInfoRequest proto.InternalMessageInfo

func (m *SetCustomerContactInfoRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *SetCustomerContactInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SetCustomerContactInfoRequest) GetContactUserPhone() string {
	if m != nil {
		return m.ContactUserPhone
	}
	return ""
}

func (m *SetCustomerContactInfoRequest) GetContactUserEmail() string {
	if m != nil {
		return m.ContactUserEmail
	}
	return ""
}

type CustomerContactInfoResponse struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	InfoID               string   `protobuf:"bytes,2,opt,name=infoID,proto3" json:"infoID,omitempty"`
	ContactUserPhone     string   `protobuf:"bytes,3,opt,name=contactUserPhone,proto3" json:"contactUserPhone,omitempty"`
	ContactUserEmail     string   `protobuf:"bytes,4,opt,name=contactUserEmail,proto3" json:"contactUserEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerContactInfoResponse) Reset()         { *m = CustomerContactInfoResponse{} }
func (m *CustomerContactInfoResponse) String() string { return proto.CompactTextString(m) }
func (*CustomerContactInfoResponse) ProtoMessage()    {}
func (*CustomerContactInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{29}
}
func (m *CustomerContactInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerContactInfoResponse.Unmarshal(m, b)
}
func (m *CustomerContactInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerContactInfoResponse.Marshal(b, m, deterministic)
}
func (dst *CustomerContactInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerContactInfoResponse.Merge(dst, src)
}
func (m *CustomerContactInfoResponse) XXX_Size() int {
	return xxx_messageInfo_CustomerContactInfoResponse.Size(m)
}
func (m *CustomerContactInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerContactInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerContactInfoResponse proto.InternalMessageInfo

func (m *CustomerContactInfoResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CustomerContactInfoResponse) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *CustomerContactInfoResponse) GetContactUserPhone() string {
	if m != nil {
		return m.ContactUserPhone
	}
	return ""
}

func (m *CustomerContactInfoResponse) GetContactUserEmail() string {
	if m != nil {
		return m.ContactUserEmail
	}
	return ""
}

type UpdateCustomerInfoRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	InfoID               string          `protobuf:"bytes,3,opt,name=infoID,proto3" json:"infoID,omitempty"`
	Fio                  string          `protobuf:"bytes,4,opt,name=fio,proto3" json:"fio,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateCustomerInfoRequest) Reset()         { *m = UpdateCustomerInfoRequest{} }
func (m *UpdateCustomerInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCustomerInfoRequest) ProtoMessage()    {}
func (*UpdateCustomerInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{30}
}
func (m *UpdateCustomerInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCustomerInfoRequest.Unmarshal(m, b)
}
func (m *UpdateCustomerInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCustomerInfoRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateCustomerInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCustomerInfoRequest.Merge(dst, src)
}
func (m *UpdateCustomerInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCustomerInfoRequest.Size(m)
}
func (m *UpdateCustomerInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCustomerInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCustomerInfoRequest proto.InternalMessageInfo

func (m *UpdateCustomerInfoRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *UpdateCustomerInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateCustomerInfoRequest) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *UpdateCustomerInfoRequest) GetFio() string {
	if m != nil {
		return m.Fio
	}
	return ""
}

type UpdateCustomerContactInfoRequest struct {
	PartnerContext       *PartnerContext `protobuf:"bytes,1,opt,name=partnerContext,proto3" json:"partnerContext,omitempty"`
	UserID               string          `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	InfoID               string          `protobuf:"bytes,3,opt,name=infoID,proto3" json:"infoID,omitempty"`
	ContactUserPhone     string          `protobuf:"bytes,4,opt,name=contactUserPhone,proto3" json:"contactUserPhone,omitempty"`
	ContactUserEmail     string          `protobuf:"bytes,5,opt,name=contactUserEmail,proto3" json:"contactUserEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateCustomerContactInfoRequest) Reset()         { *m = UpdateCustomerContactInfoRequest{} }
func (m *UpdateCustomerContactInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCustomerContactInfoRequest) ProtoMessage()    {}
func (*UpdateCustomerContactInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_requisites_0e87d00f5fe60b78, []int{31}
}
func (m *UpdateCustomerContactInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCustomerContactInfoRequest.Unmarshal(m, b)
}
func (m *UpdateCustomerContactInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCustomerContactInfoRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateCustomerContactInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCustomerContactInfoRequest.Merge(dst, src)
}
func (m *UpdateCustomerContactInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCustomerContactInfoRequest.Size(m)
}
func (m *UpdateCustomerContactInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCustomerContactInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCustomerContactInfoRequest proto.InternalMessageInfo

func (m *UpdateCustomerContactInfoRequest) GetPartnerContext() *PartnerContext {
	if m != nil {
		return m.PartnerContext
	}
	return nil
}

func (m *UpdateCustomerContactInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateCustomerContactInfoRequest) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *UpdateCustomerContactInfoRequest) GetContactUserPhone() string {
	if m != nil {
		return m.ContactUserPhone
	}
	return ""
}

func (m *UpdateCustomerContactInfoRequest) GetContactUserEmail() string {
	if m != nil {
		return m.ContactUserEmail
	}
	return ""
}

func init() {
	proto.RegisterType((*PartnerContext)(nil), "api.PartnerContext")
	proto.RegisterType((*Header)(nil), "api.Header")
	proto.RegisterType((*SetBankDetailRequest)(nil), "api.SetBankDetailRequest")
	proto.RegisterType((*SetBankDetailResponse)(nil), "api.SetBankDetailResponse")
	proto.RegisterType((*GetBankDetailsRequest)(nil), "api.GetBankDetailsRequest")
	proto.RegisterType((*GetBankDetailRequest)(nil), "api.GetBankDetailRequest")
	proto.RegisterType((*GetBankDetailResponse)(nil), "api.GetBankDetailResponse")
	proto.RegisterType((*BankDetailInfo)(nil), "api.BankDetailInfo")
	proto.RegisterType((*GetBankDetailsResponse)(nil), "api.GetBankDetailsResponse")
	proto.RegisterType((*SetBusinessInfoRequest)(nil), "api.SetBusinessInfoRequest")
	proto.RegisterType((*InfoIdResponse)(nil), "api.InfoIdResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "api.GetInfoRequest")
	proto.RegisterType((*BusinessInfoResponse)(nil), "api.BusinessInfoResponse")
	proto.RegisterType((*SetBusinessContactInfoRequest)(nil), "api.SetBusinessContactInfoRequest")
	proto.RegisterType((*BusinessContactInfoResponse)(nil), "api.BusinessContactInfoResponse")
	proto.RegisterType((*UpdateBusinessInfoRequest)(nil), "api.UpdateBusinessInfoRequest")
	proto.RegisterType((*UpdateBusinessContactInfoRequest)(nil), "api.UpdateBusinessContactInfoRequest")
	proto.RegisterType((*UpdateDefaultPaymentsRequest)(nil), "api.UpdateDefaultPaymentsRequest")
	proto.RegisterType((*UpdateDefaultPaymentsResponse)(nil), "api.UpdateDefaultPaymentsResponse")
	proto.RegisterType((*SetBankCardRequest)(nil), "api.SetBankCardRequest")
	proto.RegisterType((*SetBankCardResponse)(nil), "api.SetBankCardResponse")
	proto.RegisterType((*GetBankCardsRequest)(nil), "api.GetBankCardsRequest")
	proto.RegisterType((*GetBankCardRequest)(nil), "api.GetBankCardRequest")
	proto.RegisterType((*GetBankCardResponse)(nil), "api.GetBankCardResponse")
	proto.RegisterType((*BankCardInfo)(nil), "api.BankCardInfo")
	proto.RegisterType((*GetBankCardsResponse)(nil), "api.GetBankCardsResponse")
	proto.RegisterType((*SetCustomerInfoRequest)(nil), "api.SetCustomerInfoRequest")
	proto.RegisterType((*CustomerInfoResponse)(nil), "api.CustomerInfoResponse")
	proto.RegisterType((*SetCustomerContactInfoRequest)(nil), "api.SetCustomerContactInfoRequest")
	proto.RegisterType((*CustomerContactInfoResponse)(nil), "api.CustomerContactInfoResponse")
	proto.RegisterType((*UpdateCustomerInfoRequest)(nil), "api.UpdateCustomerInfoRequest")
	proto.RegisterType((*UpdateCustomerContactInfoRequest)(nil), "api.UpdateCustomerContactInfoRequest")
}

func init() {
	proto.RegisterFile("api/proto/requisites.proto", fileDescriptor_requisites_0e87d00f5fe60b78)
}

var fileDescriptor_requisites_0e87d00f5fe60b78 = []byte{
	// 1130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0x4d, 0x6f, 0x23, 0x35,
	0x18, 0xd6, 0xcc, 0x24, 0xd3, 0xe4, 0x6d, 0x37, 0x64, 0xdd, 0x6e, 0x14, 0xba, 0xbb, 0x28, 0x32,
	0x68, 0x55, 0x21, 0xd4, 0x45, 0x20, 0xb8, 0xec, 0xa9, 0xb4, 0x6c, 0x9a, 0x03, 0x6c, 0x35, 0xb0,
	0x3f, 0xc0, 0x9d, 0x71, 0x12, 0xd3, 0x64, 0x66, 0x76, 0x3c, 0x91, 0x36, 0x5c, 0xd0, 0x4a, 0x1c,
	0xe1, 0x82, 0xb4, 0x17, 0x7e, 0x00, 0x67, 0x04, 0x77, 0x24, 0x2e, 0x9c, 0xf8, 0x03, 0xfc, 0x02,
	0xee, 0x5c, 0xb9, 0x20, 0x7b, 0xbe, 0xbf, 0x42, 0x46, 0x4a, 0x82, 0x10, 0xdc, 0xec, 0xc7, 0x6f,
	0xec, 0xd7, 0xcf, 0xf3, 0xbc, 0x63, 0xbb, 0x85, 0x63, 0xe2, 0xb2, 0x87, 0xae, 0xe7, 0xf8, 0xce,
	0x43, 0x8f, 0x3e, 0x5b, 0x30, 0xce, 0x7c, 0xca, 0x4f, 0x25, 0x80, 0x34, 0xe2, 0x32, 0x7c, 0x09,
	0x9d, 0x2b, 0xe2, 0xf9, 0x36, 0xf5, 0xce, 0x1d, 0xdb, 0xa7, 0xcf, 0x7d, 0x74, 0x0f, 0xda, 0x6e,
	0x80, 0x8c, 0x2e, 0xfa, 0xca, 0x40, 0x39, 0x69, 0x1b, 0x09, 0x80, 0xfa, 0xb0, 0x67, 0x06, 0x81,
	0x7d, 0x75, 0xa0, 0x9c, 0x1c, 0x18, 0x51, 0x17, 0x9f, 0x82, 0x7e, 0x49, 0x89, 0x45, 0x3d, 0x84,
	0xa0, 0x61, 0x3a, 0x16, 0x95, 0x3f, 0xbe, 0x65, 0xc8, 0x36, 0xea, 0x82, 0x36, 0xe7, 0x13, 0xf9,
	0x9b, 0xb6, 0x21, 0x9a, 0xf8, 0x37, 0x15, 0x8e, 0x3e, 0xa1, 0xfe, 0x07, 0xc4, 0xbe, 0xb9, 0xa0,
	0x3e, 0x61, 0x33, 0x83, 0x3e, 0x5b, 0x50, 0xee, 0xa3, 0x47, 0xd0, 0x71, 0x33, 0x29, 0xc9, 0x89,
	0xf6, 0xdf, 0x39, 0x3c, 0x25, 0x2e, 0x3b, 0xcd, 0x66, 0x6b, 0xe4, 0x42, 0x51, 0x0f, 0xf4, 0x05,
	0x97, 0xa9, 0x07, 0x4b, 0x85, 0x3d, 0xf4, 0x1a, 0x80, 0x25, 0x57, 0xf9, 0x98, 0xcc, 0x69, 0x5f,
	0x93, 0x63, 0x29, 0x04, 0xbd, 0x0f, 0xbd, 0x6b, 0x62, 0xdf, 0x8c, 0x2c, 0x6a, 0xfb, 0x6c, 0xcc,
	0x4c, 0xe2, 0x33, 0xc7, 0x3e, 0x17, 0xbb, 0x68, 0xc8, 0xd8, 0x8a, 0x51, 0x74, 0x0c, 0x2d, 0x31,
	0x22, 0x67, 0x6d, 0xca, 0xc8, 0xb8, 0x2f, 0x79, 0x60, 0xfe, 0xb2, 0xaf, 0x4b, 0x5c, 0xb6, 0x05,
	0x7f, 0xc4, 0xb2, 0x3c, 0xca, 0x79, 0x7f, 0x4f, 0xc2, 0x51, 0x17, 0x0d, 0x60, 0xdf, 0x74, 0x3c,
	0xef, 0xcc, 0x34, 0x9d, 0x85, 0xed, 0xf7, 0x5b, 0x72, 0x34, 0x0d, 0xa1, 0x13, 0x78, 0xc5, 0x9c,
	0x52, 0xf3, 0x86, 0xd9, 0x93, 0x28, 0xaa, 0x2d, 0xa3, 0xf2, 0x30, 0xfe, 0x52, 0x81, 0x3b, 0x39,
	0x6e, 0xb9, 0xeb, 0xd8, 0x9c, 0xa2, 0xd7, 0x41, 0x9f, 0x4a, 0x95, 0x42, 0x52, 0xf7, 0x25, 0xa9,
	0x81, 0x70, 0x46, 0x38, 0x24, 0x52, 0x89, 0xdd, 0x12, 0x33, 0x99, 0x86, 0xd0, 0x1b, 0x70, 0xcb,
	0xa2, 0x63, 0xb2, 0x98, 0xf9, 0xc1, 0xfc, 0x92, 0xd1, 0x96, 0x91, 0x05, 0xf1, 0x0c, 0xee, 0x0c,
	0xd3, 0x59, 0xf0, 0x6d, 0x4a, 0x8c, 0xbf, 0x56, 0xe0, 0x68, 0xb8, 0x33, 0x43, 0xe5, 0x38, 0xd2,
	0x0a, 0x1c, 0xe1, 0x3f, 0xd4, 0xdc, 0xf6, 0x37, 0x2d, 0xc2, 0x7f, 0xca, 0xd3, 0x45, 0xcb, 0x41,
	0x99, 0xe5, 0x7e, 0x51, 0xa1, 0x93, 0x30, 0x3e, 0xb2, 0xc7, 0x4e, 0x9e, 0x48, 0xe5, 0xef, 0x88,
	0x54, 0x6b, 0x10, 0xa9, 0xad, 0x4d, 0x64, 0xa3, 0x82, 0xc8, 0x66, 0x39, 0x91, 0xfa, 0x4a, 0x22,
	0xf7, 0xd6, 0x22, 0xb2, 0xb5, 0x26, 0x91, 0xed, 0x32, 0x22, 0x3f, 0x87, 0x5e, 0xbe, 0x76, 0xeb,
	0xb8, 0xf7, 0x11, 0x74, 0xae, 0x33, 0x32, 0xf4, 0xd5, 0x81, 0x16, 0xd7, 0x5c, 0x56, 0x21, 0x23,
	0x17, 0x8a, 0x5f, 0x6a, 0xd0, 0x13, 0x9f, 0xaf, 0x05, 0x67, 0x36, 0xe5, 0x5c, 0xc6, 0x6c, 0xb9,
	0x96, 0x4d, 0x67, 0xee, 0x12, 0x7b, 0x99, 0xaa, 0xa4, 0x34, 0x24, 0x8e, 0x2f, 0x66, 0xdb, 0xa1,
	0x88, 0xa2, 0x29, 0x90, 0x1b, 0xd7, 0x0d, 0xe5, 0x13, 0x4d, 0xa1, 0xa8, 0x33, 0xf1, 0xec, 0xa8,
	0x34, 0x44, 0x1b, 0x61, 0x38, 0x98, 0xd1, 0x09, 0x99, 0x9d, 0x65, 0xea, 0x23, 0x83, 0x09, 0xe5,
	0xdc, 0xe9, 0x92, 0x33, 0x33, 0x09, 0x0b, 0x95, 0xcb, 0xc1, 0x62, 0x36, 0x73, 0xca, 0xe8, 0xf8,
	0x29, 0xa7, 0xde, 0xe3, 0xd1, 0x93, 0xb0, 0x52, 0x32, 0x18, 0x7a, 0x0b, 0x6e, 0xc7, 0xfd, 0x2b,
	0x87, 0x33, 0x61, 0x46, 0x59, 0x2a, 0x6d, 0xa3, 0x38, 0x20, 0xa2, 0x27, 0x9e, 0xb3, 0xb0, 0x2d,
	0xfe, 0xd8, 0xf1, 0xce, 0x4c, 0x81, 0xf1, 0xfe, 0x7e, 0x10, 0x5d, 0x18, 0xc0, 0x1f, 0x41, 0x47,
	0x68, 0x31, 0xb2, 0xea, 0x79, 0xa1, 0x07, 0x3a, 0x13, 0x3f, 0x8b, 0x69, 0x0f, 0x7a, 0xf8, 0x85,
	0x02, 0x9d, 0x21, 0xf5, 0xb7, 0x2e, 0xef, 0x31, 0xb4, 0x44, 0xeb, 0xd3, 0xa5, 0x1b, 0x68, 0x7b,
	0xcb, 0x88, 0xfb, 0xf8, 0x4f, 0x15, 0x8e, 0xb2, 0x3e, 0xdb, 0xc0, 0xce, 0xfe, 0x37, 0xd4, 0x9a,
	0x86, 0xfa, 0x4e, 0x85, 0xfb, 0xa9, 0x42, 0x17, 0x42, 0x12, 0x73, 0xfb, 0x86, 0x78, 0x00, 0x1d,
	0x33, 0x58, 0x2a, 0xda, 0x78, 0xa0, 0x50, 0x0e, 0x45, 0x6f, 0xc3, 0x61, 0x0a, 0x89, 0x37, 0x1f,
	0x88, 0x56, 0x36, 0x84, 0xde, 0x84, 0x6e, 0x1a, 0x9e, 0x3a, 0x76, 0x74, 0x84, 0x16, 0xf0, 0x5c,
	0xec, 0x87, 0x73, 0xf1, 0x29, 0xd6, 0x0b, 0xb1, 0x12, 0xc7, 0x5f, 0xa9, 0x70, 0xb7, 0x94, 0xa5,
	0x4d, 0xb8, 0xf5, 0xdf, 0x47, 0xc7, 0xf7, 0x1a, 0xbc, 0xfa, 0xd4, 0xb5, 0x88, 0x4f, 0x77, 0x76,
	0x46, 0x24, 0xe4, 0x69, 0xab, 0x4a, 0xbd, 0x51, 0x59, 0xea, 0xcd, 0x42, 0xa9, 0xeb, 0xc5, 0x52,
	0xdf, 0x5b, 0x51, 0xea, 0xad, 0xf5, 0x4a, 0xbd, 0xbd, 0x5e, 0xa9, 0xc3, 0xba, 0xa5, 0xbe, 0x5f,
	0xab, 0xd4, 0x0f, 0xaa, 0x4a, 0xfd, 0x67, 0x15, 0x06, 0x59, 0xc9, 0x76, 0x55, 0xed, 0x55, 0xca,
	0x15, 0x6d, 0xdf, 0xa8, 0x63, 0xfb, 0x66, 0x3d, 0xdb, 0xeb, 0x35, 0x6c, 0xbf, 0x57, 0x61, 0xfb,
	0x97, 0x0a, 0xdc, 0x0b, 0x38, 0xbc, 0x08, 0xee, 0x6a, 0x57, 0x64, 0x39, 0xa7, 0xb6, 0xcf, 0xff,
	0xe1, 0x97, 0xce, 0x0c, 0xee, 0x57, 0xa4, 0x55, 0xe7, 0xf3, 0xf4, 0x00, 0x3a, 0x56, 0xe6, 0xf7,
	0x32, 0x8f, 0x96, 0x91, 0x43, 0xf1, 0x8f, 0x0a, 0xa0, 0xf0, 0x71, 0x7b, 0x4e, 0x3c, 0x6b, 0xab,
	0x7b, 0xef, 0x82, 0xe6, 0x12, 0x3b, 0xdc, 0xb3, 0x68, 0x8a, 0xb7, 0x82, 0x49, 0x3c, 0xeb, 0xd2,
	0x99, 0x89, 0xed, 0x04, 0x8e, 0x49, 0x21, 0x62, 0x26, 0xfa, 0xdc, 0x65, 0x5e, 0x74, 0xb3, 0x0f,
	0x7b, 0xd8, 0x87, 0xc3, 0x4c, 0xd2, 0x35, 0x3f, 0xdc, 0x62, 0x85, 0x24, 0xbb, 0xa0, 0x27, 0x94,
	0x09, 0xb9, 0x11, 0x73, 0x86, 0x6f, 0xf0, 0x34, 0x84, 0x3f, 0x83, 0xc3, 0x61, 0xb2, 0xea, 0x76,
	0xdf, 0xdf, 0x2f, 0x14, 0x40, 0xc3, 0x1d, 0xe9, 0x92, 0x30, 0xa2, 0xa5, 0x19, 0xc1, 0x3f, 0x29,
	0x99, 0x0d, 0x6f, 0x86, 0xe6, 0x8d, 0x99, 0x20, 0x2f, 0x98, 0x5e, 0x14, 0xec, 0x1b, 0x05, 0x0e,
	0xa2, 0xec, 0xe5, 0xeb, 0x35, 0x49, 0x4a, 0x29, 0x4b, 0x4a, 0xad, 0x4a, 0x4a, 0x5b, 0x91, 0x54,
	0x63, 0x55, 0x52, 0xcd, 0x62, 0x52, 0x5e, 0xfc, 0x87, 0x95, 0xd0, 0x45, 0x75, 0x58, 0x7d, 0x0f,
	0x0e, 0xae, 0x53, 0x1b, 0x0a, 0xdf, 0x81, 0xb7, 0xe3, 0x77, 0x60, 0x34, 0x60, 0x64, 0xc2, 0xf0,
	0x17, 0xf2, 0x09, 0x78, 0xbe, 0xe0, 0xbe, 0x33, 0xa7, 0xde, 0xd6, 0x0f, 0x89, 0x2e, 0x68, 0xc9,
	0xc5, 0x47, 0x1b, 0x8f, 0x9e, 0x60, 0x0a, 0x47, 0xd9, 0xd5, 0x37, 0x71, 0xd5, 0xea, 0x82, 0x36,
	0x66, 0x4e, 0xbc, 0x0c, 0x73, 0xf0, 0xaf, 0x8a, 0xbc, 0x02, 0x47, 0x4b, 0xed, 0xea, 0x50, 0x2c,
	0x3b, 0xa2, 0xb4, 0x1a, 0x47, 0x54, 0xa3, 0xe2, 0x88, 0xfa, 0x41, 0x81, 0xbb, 0xa5, 0x7b, 0xd9,
	0x04, 0x7b, 0xdb, 0x4a, 0xfa, 0x5b, 0x25, 0xba, 0x4e, 0xee, 0xcc, 0x6f, 0x55, 0x97, 0x92, 0xd0,
	0x20, 0x8d, 0xc4, 0x20, 0xbf, 0x2b, 0xd1, 0xc5, 0x69, 0xd7, 0x1e, 0xa9, 0xca, 0xb1, 0x4c, 0x86,
	0x46, 0x0d, 0x19, 0x9a, 0xe5, 0x32, 0x5c, 0xeb, 0xf2, 0xff, 0x12, 0xef, 0xfe, 0x15, 0x00, 0x00,
	0xff, 0xff, 0x2b, 0x2f, 0x17, 0x4d, 0xb5, 0x18, 0x00, 0x00,
}
